name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify directory structure
      run: |
        pwd
        ls -la

    - name: List project directory contents
      run: ls -la express-pug-sqlite-blog || echo "Directory express-pug-sqlite-blog not found"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: ./express-pug-sqlite-blog
      run: npm ci

    - name: Run tests
      working-directory: ./express-pug-sqlite-blog
      run: npm test
